spring:
  application:
    name: dtx-notifymsg-demo-pay
  profiles: 
    active: local
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8

server:
  servlet:
    context-path: /pay
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  use-forward-headers: true
